 - name: iamin
   hosts:
        linux
   become: yes
   tasks:
     - name: g++ install
       yum:
         name: g++
         state: latest
     - name: python install
       apt:
          name: python
          state: latest
    #  - name: docker uninstall
    #    apt:
    #      name: docker.io
    #      state: absent