 - name: iamin
   hosts:
        linux
   become: yes
   tasks:
     - name: g++ install
       yum:
         name: gcc
         state: latest
     - name: python install
       apt:
          name: python
          state: absent
    #  - name: docker uninstall
    #    apt:
    #      name: docker.io
    #      state: absent