 - name: iamin
   hosts:
        linux
        linux2
   remote_user: root
   tasks:
     - name: python is there
       yum:
         name: gcc
         state: latest
     - name: g++ is there
       apt:
          name: g++
          state: latest