 - name: iamin
   hosts:
        linux
        
   remote_user: root
   tasks:
     - name: gcc uninstall
       yum:
         name: gcc
         state: latest
    #  - name: g++ uninstall
    #    apt:
    #       name: g++
    #       state: absent
    #  - name: docker uninstall
    #    apt:
    #      name: docker.io
    #      state: absent